charts/pxc-db/values.yaml

s3 interface can be used in multiple cloud providers. So endpointUrl could be useful for anyone using non standard s3 interface of aws. eg: DigitalOcean

Add example for changing endpoint url for s3

---

.github/workflows/test.yaml

There was some warning which I missed that this option is obsolete, `kind` version 0.7.0+ supports this by default.
`Dynamic PersistentVolume Support is greatly enhanced with rancher.io/localhost-path integration out of the box`

CLOUD-603 - remove obsolete install_local_path_provisioner for kind cluster

---

charts/pxc-db/Chart.yaml
charts/pxc-db/templates/cluster.yaml

```
pxc:
imagePullSecrets:
- name: "some_secret"
haproxy:
imagePullSecrets:
- name: "some_secret"
```
Will result in the following error, `block sequence entries are not allowed in this context`, because the whitespace control is broken.

K8SPXC-562 Fix broken haproxy imagePullSecrets

---

charts/pxc-db/Chart.yaml
charts/pxc-db/crds/crd.yaml
charts/pxc-operator/Chart.yaml
charts/pxc-operator/crds/crd.yaml

When keeping a YAML manifest in sync using GitOps tools like ArgoCD, these tools report the manifest being out of sync when the live manifest in the cluster differs from the desired manifest in the source Git/Helm repository.
The `PerconaXtraDBBackup` CRD has an explicit empty list for its `.spec.names.shortNames` property. This is actually the default value, and in that case it apparently gets removed from the live manifest by k8s when applied. This causes the manifest to never become synced in tools like ArgoCD.
The fix is to remove the default empty value from the manifest, which will result in the same configuration on the cluster, but this time in sync with the source manifest.
This is how the issue manifests itself in ArgoCD specifically:

Remove empty .spec.names.shortNames default from backup CRD.

---

charts/psmdb-db/values.yaml

When `DNSsuffix` is prepended with a dot `.` it renders a double dot `..` in the domain. The example in the `values.yaml` should have this dot `.` removed.

Fixed dns-suffix in values.yaml

---

charts/pxc-db/templates/cluster.yaml

I have found a solution to resolve the bug mentioned in the above jira ticket. I have added a condition in 'cluster.yaml' file, after running the chart the cron job are no longer are getting created as the backup is disabled.

Issue K8SPXC-620 in jira. Backup cronjobs created for disabled backups

---

charts/pxc-db/Chart.yaml
charts/pxc-db/templates/_helpers.tpl
charts/pxc-db/templates/cluster.yaml
charts/pxc-db/templates/s3-secret.yaml
charts/pxc-db/values.yaml

This makes it possible to specify the S3 credentials from the Helm chart by automatically creating a k8s Secret for them.

Allow S3 credentials to be specified in plain text

---

charts/pxc-db/Chart.yaml
charts/pxc-db/templates/cluster.yaml

Support additional configuration for haproxy and proxysql to allow
users to specify several operator-supported options to configure the
Service objects.
- externalTrafficPolicy
- loadBalancerSourceRanges
- serviceAnnotations
- serviceType
This should provide the correct knobs for configuring external load
balancers on AWS, for example.
Signed-off-by: Chris Gianelloni <cgianelloni@applause.com>

Allow configuring the Service objects created

---

README.md

The main `README.md` file omits the `charts` folder in the link to the individual chart `README.md` files. Might as well make a PR for you guys :)

Fixes invalid links to chart readme files

---

charts/psmdb-db/templates/cluster.yaml

This PR simply adds tolerations for each pod templates in the cluster cr template.
This has been tested, except for the arbiter pods.

Add support for tolerations

---

charts/pxc-db/Chart.yaml
charts/pxc-db/README.md
charts/pxc-db/templates/cluster.yaml
charts/pxc-db/values.yaml

Support for PXC pod sidecars have been added in 1.8.0 release of the
operator. This makes it configurable.

Add support for pxc.sidecars

---

charts/psmdb-db/templates/cluster.yaml

It acutally matches the current documentation.

Fix backup.serviceAccountName not being interpolated

---

charts/pxc-db/Chart.yaml
charts/pxc-db/templates/cluster.yaml

There is no `enabled` field in `.PerconaXtraDBCluster.spec.backup`.
For this reason, when I'm turn off the backup:
```diff
diff --git a/charts/pxc-db/values.yaml b/charts/pxc-db/values.yaml
index 567736b..b80e0c4 100644
--- a/charts/pxc-db/values.yaml
+++ b/charts/pxc-db/values.yaml
@@ -374,7 +374,7 @@ pmm:
limits: {}
backup:
-  enabled: true
+  enabled: false
image: ""
imagePullSecrets: []
```
I see the error:
```bash
Error: UPGRADE FAILED: release xtradb failed, and has been rolled back due to atomic being set: cannot patch "xtradb-pxc-db" with kind PerconaXtraDBCluster: admission webhook "validationwebhook.pxc.percona.com" denied the request: json: unknown field "enabled"
deploying "xtradb": install: exit status 1
```
Signed-off-by: Renat Galiev <renat@galiev.net>

Fix disabling backup for Percona XtraDB Cluster Databases

---

charts/pxc-db/Chart.yaml
charts/pxc-db/templates/cluster.yaml
charts/pxc-db/values.yaml

Percona XtraDB Cluster Databases support [pxc.podSecurityContext](https://www.percona.com/doc/kubernetes-operator-for-pxc/operator.html#pxc-podsecuritycontext) option, it becomes possible to configure this parameter.
Also CustomResource PerconaXtraDBCluster supports options: proxysql.podSecurityContext and haproxy.podSecurityContext.
Signed-off-by: Renat Galiev <renat@galiev.net>

enable support podSecurityContext configuration for Percona XtraDB Cluster Databases

---

charts/pxc-db/Chart.yaml
charts/pxc-db/README.md
charts/pxc-db/production-values.yaml
charts/pxc-db/templates/cluster.yaml
charts/pxc-db/values.yaml

In an airgap environment, we need to set the imagePullPolicy to Never for images.  This PR allows us to set it for the missed images, as well as the imagePullSecrets.

Additional image pull attributes

---

charts/pxc-operator/Chart.yaml
charts/pxc-operator/README.md
charts/pxc-operator/templates/deployment.yaml

When trying to install `pxc-operator` in number-only namespace, e.g.
```
helm -n 7129496 install my-operator percona/pxc-operator
```
Helm fails with cryptic error:
```
Error: INSTALLATION FAILED: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 7, error found in #10 byte of ...|,"value":7129496},{"|..., bigger context ...|rator"],"env":[{"name":"WATCH_NAMESPACE","value":7129496},{"name":"POD_NAME","valueFrom":{"fieldRef"|...
```
Quoting namespace will fix errors like that.

fix: quote namespace in pxc-operator deploy

---

charts/pxc-db/Chart.yaml
charts/pxc-db/README.md
charts/pxc-db/production-values.yaml
charts/pxc-db/templates/cluster.yaml
charts/pxc-db/values.yaml

Adding sidecarVolume support to the pxc-db, as it is already supported by the pxc-operator
Fixes K8SPXC-1048 (broken StatefulSet due a sidecarVolume)

K8SPXC-1048 - fixing sidecarVolumes in pxc-db chart

---

charts/ps-db/.helmignore
charts/ps-db/Chart.yaml
charts/ps-db/README.md
charts/ps-db/crds/crd.yaml
charts/ps-db/templates/NOTES.txt
charts/ps-db/templates/_helpers.tpl
charts/ps-db/templates/cluster-secret.yaml
charts/ps-db/templates/cluster.yaml
charts/ps-db/values.yaml
charts/ps-operator/.helmignore
charts/ps-operator/Chart.yaml
charts/ps-operator/README.md
charts/ps-operator/crds/crd.yaml
charts/ps-operator/templates/NOTES.txt
charts/ps-operator/templates/_helpers.tpl
charts/ps-operator/templates/configmap.yaml
charts/ps-operator/templates/deployment.yaml
charts/ps-operator/templates/role-binding.yaml
charts/ps-operator/templates/role.yaml
charts/ps-operator/values.yaml

Few things:
1. volumes are specified as `volumeSpec.pvc` not `volumeSpec.persistentVolumeClaim` because it's shorter and `pxc-db` uses `persistence: enabled` - we don't use it here
2. `secrets.passwords` is used to construct secret with default name unless `secretsName` is specified and then helm uses whatever user or operator created
3. this helm chart currently is not dealing (constructing) ssl/tls secret - it will use whatever the user or operator created

K8SPS-68 - Initial helm chart for PS operator

---

charts/psmdb-db/Chart.yaml
charts/psmdb-db/README.md
charts/psmdb-db/production-values.yaml
charts/psmdb-db/templates/cluster.yaml
charts/psmdb-db/values.yaml

**Background**
The `crVersion` field should reside in the PSMDB Manifest.
Currently, the template does not contain this field.
the field is used by the PSMDB Operator, for example [here](https://github.com/percona/percona-server-mongodb-operator/blob/98637ec48ea6644f8e320ffd97de19f3fcecbc46/pkg/psmdb/statefulset.go#L224)
and many more cases.
I myself got to the issue since the `isEncryptionEnabled` function was not behaving as expected
**Summary**
- add `crVersion` field to the `cluster.yaml` Spec
- update `Chart.yaml` version to `version: 1.12.5`
- add default value in values file `crVersion: 1.12.0`
- add `crVersion` definition to the README

fix missing crVersion in the psmdb-db cluster template

---

charts/pxc-operator/Chart.yaml
charts/pxc-operator/README.md
charts/pxc-operator/templates/role-binding.yaml
charts/pxc-operator/templates/role.yaml
charts/pxc-operator/values.yaml

Adds the option to skip ServiceAccounts and RBAC. Similar to how it is done in https://github.com/percona/percona-helm-charts/tree/main/charts/pg-operator

CLOUD-758 - Add option to skip SAs and RBAC

---

charts/pg-db/Chart.yaml
charts/pg-db/templates/cluster.yaml

Helm install fails with pg-db 2.2.0 due to the existence of a duplicate "pause" key in the cluster.yaml template This PR removes the duplicate.

K8SPG-402 Remove duplicate "pause" key from cluster.yaml

---

charts/pxc-db/Chart.yaml
charts/pxc-db/templates/NOTES.txt

In this previous PR: https://github.com/percona/percona-helm-charts/commit/fdcb6fbf2da6cf5f2ee92c66f15b9566bcbef03a a change was made to allow the variable "clusterSecretName" to be configured. 
Additionally, if the clusterSecretName wasn't specified, the suffix "-secret" was added to the fullname of the database.
The NOTES.txt was emitting on the fullname and not the fullname-secrets so the instructions would be incorrect in every case.

K8SPXC-1283 - Update NOTES.txt to correct secret name.

---

charts/pxc-operator/Chart.yaml
charts/pxc-operator/templates/deployment.yaml

When using the container security context _readOnlyRootFileSystem_ the container cannot start because it cannot write to _/tmp_.
This adds an automatic _/tmp_ mount when _readOnlyRootFileSystem_ security context is set.

K8SPXC-1291 - Add automatic /tmp mount when readOnlyRootFileSystem is set

---

charts/pxc-db/Chart.yaml
charts/pxc-db/templates/cluster-secret.yaml
charts/pxc-db/templates/cluster-ssl-secret.yaml
charts/pxc-db/templates/cluster.yaml
charts/pxc-db/templates/s3-secret.yaml
charts/pxc-db/values.yaml
charts/pxc-operator/Chart.yaml
charts/pxc-operator/templates/deployment.yaml
charts/pxc-operator/templates/role-binding.yaml
charts/pxc-operator/templates/role.yaml

Add namespace information into templates so that they can be used in GitOps way (generate with `helm template` and store in git).
This closes also this PR: https://github.com/percona/percona-helm-charts/pull/241

CLOUD-767 - include namespace in metadata for pxc-db and pxc-operator

---

charts/psmdb-db/Chart.yaml
charts/psmdb-db/README.md
charts/psmdb-db/templates/cluster.yaml

This is to address issues encountered in the link below. Basically, PSMDBBackup aren't working when using `serviceAccountName` because the entire cluster is using `default`  when using the psmdb-db chart. Since the crd supports serviceAccoountName already, this change adds the ability to set `serviceAccountName` as needed. Ideally, we would want just the specific container to have this kind of access. After some research, it doesn't seem possible to container level service account.
https://forums.percona.com/t/how-to-setup-aws-s3-storage-backup-using-service-account-irsa/21672

K8SPSMDB-997 - Add serviceAccountName to the existing resources

---

charts/pmm/Chart.yaml
charts/pmm/templates/ingress.yaml

1. Disable hardcode 443 port
2. Add an annotation according to the topic in the forum: https://forums.percona.com/t/pmm-server-deployed-on-k8s-failed-to-establish-two-way-communication-channel/22708

Fix ingress for grpc.

---

charts/pg-operator/Chart.yaml
charts/pg-operator/README.md
charts/pg-operator/templates/deployment.yaml

Fixes: https://github.com/percona/percona-helm-charts/issues/275

K8SPG-495 - Fix watchAllNamespaces for pg-operator chart

---

charts/pg-db/Chart.yaml
charts/pg-db/values.yaml

Continue to roll out percona registry for better insights. Applying to PG Operator components.

cloud-831 registry-rollout

---

charts/pxc-db/Chart.yaml
charts/pxc-db/README.md
charts/pxc-db/templates/cluster.yaml
charts/pxc-db/values.yaml

Allow to specify annotations, useful for:
- argocd sync waves
- helm hooks

K8SPXC-1360 - pxc-db: add pxdbCluster annotations

---

charts/psmdb-operator/Chart.yaml
charts/psmdb-operator/README.md
charts/psmdb-operator/templates/namespace.yaml
charts/psmdb-operator/templates/role-binding.yaml
charts/psmdb-operator/templates/role.yaml
charts/psmdb-operator/values.yaml

If we specify `watchNamespace` with multiple namespaces separated with commas namespace creation will fail (because it will try to create namespace `aaa, bbb`) so now we do it in a loop for each specified namespace and only if `createNamespace` is set to `true`.
**Default is now being changed to not create a namespace unless enabled.**

K8SPSMDB-930 - psmdb-operator - Fix watchNamespace

---

charts/pg-db/Chart.yaml
charts/pg-db/templates/cluster.yaml

Hi,
This PR just fixes indentation issues that  break the use of global section in pgbackrest.
Without this fix you can't setup custom retention rules.
Whenever you add the global section according to the official docs:
```
global:
repo1-retention-full: "5"
repo1-retention-full-type: count
```
The chart errors at the render step with error:
`Error: YAML parse error on pg-db/templates/cluster.yaml: error converting YAML to JSON: yaml: line 78: did not find expected key`
This PR fixes indentation and allows correct rendering of the pgbackrest.global section

K8SPG-524  - pg-db - fix for pgbackrest global section fails to render

---

charts/pg-db/Chart.yaml
charts/pg-db/templates/cluster.yaml

If you use pgbouncer configs with the chart, it doesn't render properly. This fixes that.

K8SPG-572 - Fix indentation issue with pgbouncer config

---

charts/pg-operator/Chart.yaml
charts/pg-operator/README.md

pg-operator README have some configuration descriptions wrongly referencing PXC instead of PG.

K8SPG-602 - pg-operator - Fix Configuration Descriptions in README

---

charts/pg-operator/Chart.yaml
charts/pg-operator/README.md
charts/pg-operator/templates/deployment.yaml
charts/pg-operator/values.yaml

This allows users to set annotations on the pods for example for Prometheus.

Allow podAnnotations via helm values for Postgres operator

---

charts/pg-db/templates/cluster.yaml

Currently the cluster template incorrectly takes only single value (object) for tolerations instead of accepting an array of objects. 
There is already an issue for this : https://github.com/percona/percona-helm-charts/issues/333
This PR fixes that issue by updating the template code that Instead of replacing with single value, replaces array of tolerations for pg-db cluster template.

K8SPG-644 - Fix tolerations iteration issue for pg-db cluster template

---

charts/psmdb-db/README.md
charts/psmdb-db/values.yaml
charts/psmdb-operator/crds/crd.yaml

https://perconadev.atlassian.net/browse/K8SPSMDB-1132

K8SPSMDB-1132: add `spec.secrets.keyFile` field 

---

charts/psmdb-operator/Chart.yaml
charts/psmdb-operator/README.md
charts/psmdb-operator/templates/deployment.yaml

When using the container security context:
```yaml
securityContext:
readOnlyRootFilesystem: true
```
then the operator fails to reconcile.
This adds an automatic `/tmp` emptyDir mount when `readOnlyRootFilesystem` is set.
This PR is borrowing the implementation from https://github.com/percona/percona-helm-charts/pull/239 but applying it to PSMDB instead of PXC

K8SPSMDB-1184 fixed by adding emptyDir mount at /tmp

---

.github/workflows/release.yaml

We'd like a separate, manual release process for Everest Helm chart, hence removing it from automated releases

Skip Everest from automated releases

---

.github/workflows/everest-release.yaml

- Use chart releaser `v1.6.0`
- Add step for releasing sub-chart

Fix Everest chart release workflow

---

charts/pmm/Chart.yaml
charts/pmm/templates/statefulset.yaml

when deploying in argo the statefulset has a diff since we don't set  the apiVersion and kind fields 
fixes #358

fix argo diff in pvc template

---

charts/everest/Chart.lock
charts/everest/Makefile
charts/everest/README.md
charts/everest/charts/common/Chart.yaml
charts/everest/charts/common/README.md
charts/everest/charts/common/templates/_db_resources_cleanup.yaml.tpl
charts/everest/charts/common/templates/_installplan_approver.yaml.tpl
charts/everest/charts/common/templates/_upgrade_checks.yaml.tpl
charts/everest/charts/everest-db-namespace/Chart.lock
charts/everest/charts/everest-db-namespace/Chart.yaml
charts/everest/charts/everest-db-namespace/README.md
charts/everest/templates/everest-monitoring/hooks.yaml
charts/everest/templates/hooks.yaml
charts/everest/values.yaml

- Adds a new pre-upgrade hook that runs upgrade checks using `everestctl upgrade --dry-run`
- This hook can be explicitly disabled
- Add some minor improvements to existing hooks to ensure they're cleaned up correctly

EVEREST-1512 | Support for running pre-upgrade checks

---

.github/workflows/everest-pr-checks.yaml
charts/everest/.helmignore
charts/everest/go.mod
charts/everest/helm.go

Since we won't be releasing v0.0.0 Helm chart, the dev-latest builds of the everestctl CLI will use the chart locally from this repo. Placing the chart files inside a embed.FS makes it easier to import these files into the codebase and also version the directory as a dependency.

Add embed.FS for Everest Helm chart

---

.github/workflows/everest-pr-checks.yaml
charts/everest/charts/everest-db-namespace/README.md
charts/everest/charts/everest-db-namespace/templates/pg.subscription.yaml
charts/everest/charts/everest-db-namespace/values.yaml

Changing `pg` to `postgresql` to maintain consistency with the DBEngine type names. See: https://github.com/percona/everest-operator/blob/main/api/v1alpha1/databaseengine_types.go#L37-L42

EVEREST-107 | Update flag names in everest-db-namespace chart

---

charts/everest/README.md
charts/everest/templates/everest-server/deployment.yaml
charts/everest/values.yaml

* Add the ability to set the `API_REQUESTS_RATE_LIMIT` env var in the Everest Deployment

[EVEREST] Add the ability to set API_REQUESTS_RATE_LIMIT

---

charts/everest/Chart.yaml
charts/everest/charts/everest-db-namespace/Chart.yaml
charts/everest/charts/everest-db-namespace/README.md

Not specifying the meta info results in error on GKE:
```sh
Error: INSTALLATION FAILED: chart requires kubeVersion: >= 1.27.0 which is incompatible with Kubernetes v1.29.10-gke.1071000
```

EVEREST-107 | Fix Everest chart kube version

---

charts/everest/README.md
charts/everest/everest-admin.yaml.tpl
charts/everest/values.yaml

Allow specifying the initial admin password with which everest is installed. Defaults to a randow 64 byte string.
This is useful in scenarios where I need to spin up a test installation and don't want to deal with having to retrieve the password. (for example, when using this chart with Tilt, I'd like to always use `admin` as the password)

EVEREST | allow specifying initial admin password in values

---

charts/everest/values.yaml

* This is done in order to maintain backward compatibility with the existing kube-state-metrics installation provided by Everest
* Since we cannot change the overrides of an existing deployment, we need to ensure that selector overrides do not change, else Helm upgrade fails

EVEREST-107 | Update selector override for kube-state-metrics

---

charts/everest/Chart.lock
charts/everest/Makefile
charts/everest/charts/common/Chart.yaml
charts/everest/charts/common/README.md
charts/everest/charts/common/templates/_operators_installer.yaml.tpl
charts/everest/charts/everest-db-namespace/Chart.lock
charts/everest/charts/everest-db-namespace/templates/hooks.yaml
charts/everest/charts/everest-db-namespace/templates/operatorgroup.yaml

* Earlier it was not possible to add more operator installations on existing DB namespaces. This is because the installplan hook ran only once, during installation (i.e, in the post-install step)
* Since you'd have to run `helm update ..` to modify an existing helm release (to add more operator installations), this PR updates the chart hook to also run on post-upgrade
* Adds an additional check to not handle the InstallPlans of installed Subscriptions
* Also uses a more generic name for the chart hook
* Revert the operatorgroup name - use the one originally used in Everest, otherwise upgrading on existing installation breaks

EVEREST-1511 | Allow adding operators to existing DB namespaces

---

charts/everest/README.md
charts/everest/templates/everest-server/accounts.secret.yaml
charts/everest/templates/everest-server/jwt.secret.yaml
charts/everest/templates/everest-server/rbac.configmap.yaml
charts/everest/templates/everest-server/settings.configmap.yaml
charts/everest/values.yaml

Fix how the Helm chart preserves Secrets and ConfigMaps during upgrades:
* The ConfigMaps and secrets need to be preserved during upgrades since they may be modified externally (via Kubectl or everestctl), and we currently do not recommend one particular way to managed them
* In the current logic, the Helm template would simply get the existing resources, iterate over the `data` key-value pairs and append them to the current template. This however does not work correctly if there are, for example, multi-line values (like in RBAC configmap, settings ConfigMap), or bools converted to strings (like `enabled`)
* The updated logic is simplified. We will include the manifest only during installs by checking `.Release.IsInstall`. However, Helm will then remove the manifests during upgrade. To …

EVEREST-107 | Secrets and ConfigMaps should not be updated during upgrades

---

charts/everest/templates/everest-operator/backupstorage-editor.clusterrole.yaml
charts/everest/templates/everest-operator/backupstorage-viewer.clusterrole.yaml
charts/everest/templates/everest-operator/databasecluster-editor.clusterrole.yaml
charts/everest/templates/everest-operator/databasecluster-viewer.clusterrole.yaml
charts/everest/templates/everest-operator/databaseclusterbackup-editor.clusterrole.yaml
charts/everest/templates/everest-operator/databaseclusterbackup-viewer.clusterrole.yaml
charts/everest/templates/everest-operator/databaseclusterrestore-editor.clusterrole.yaml
charts/everest/templates/everest-operator/databaseclusterrestore-viewer.clusterrole.yaml
charts/everest/templates/everest-operator/databaseengine-editor.clusterrole.yaml
charts/everest/templates/everest-operator/databaseengine-viewer.clusterrole.yaml
charts/everest/templates/everest-operator/deployment.yaml
charts/everest/templates/everest-operator/metrics-auth.clusterrole.yaml
charts/everest/templates/everest-operator/metrics-auth.clusterrolebinding.yaml
charts/everest/templates/everest-operator/metrics.service.yaml
charts/everest/templates/everest-operator/monitoringconfig-editor.clusterrole.yaml
charts/everest/templates/everest-operator/monitoringconfig-viewer.clusterrole.yaml

In https://github.com/percona/everest-operator/pull/597 we removed kube-rbac-proxy and migrated to go/v4 project. This commit reflects the manifest changes introduced in that PR.

EVEREST-107 Remove kube-rbac-proxy and update kubebuilder project to go/v4

---

charts/everest/Chart.lock
charts/everest/charts/common/Chart.yaml
charts/everest/charts/common/README.md
charts/everest/charts/common/templates/_db_resources_cleanup.yaml.tpl
charts/everest/charts/everest-db-namespace/Chart.lock

- update the Job RBAC so that `--wait` works correctly. Currently, without the `get` and `watch` permissions, `--wait` doesn't actually wait for the deletion and fails silently
- add appropriate hook weight so that the DB clean-up always runs first

EVEREST-1732 | Fix pre-delete hook (DB resource cleanup)

---

charts/everest/README.md
charts/everest/README.md.gotmpl

Specifying `--set` (or other equivalent flags) with `helm upgrade ..` causes Helm to reset all the other values to the ones built into the chart. To prevent this, user should specify `--reuse-values` or specify the whole set of values including the ones used for install.

EVEREST-107 | add note for upgrade

---

charts/everest/crds/everest.yaml

Following up the changes introduced in https://github.com/percona/everest-operator/pull/592 we need to add the affinity fields to the everest-operator CRD.

EVEREST-1618 add affinity

---

charts/everest/crds/olm.yaml

Hey team,
Hope you are doing alright. Thought it might be useful to remove `creationTimestamp: null` in Everest's CRD, **olm.yaml**. Please ket me know if this is used for a specific reason.
Great job!

Remove Extra creationTimestamp:null in OLM CRD

---

charts/pg-db/Chart.yaml
charts/pg-db/templates/cluster.yaml

This PR should fix the missing fields in .spec.standby by passing them all-through leaving the validation up to the operator

pg-db - Added missing PerconaPGCluster .spec.standby. fields

---

charts/everest/crds/everest.yaml

In the scope of EVEREST-1625 the `.backup.enabled` field got optional, but this change was missing in the helm manifests. 
Note: CI is going to be fixed once the operator PR https://github.com/percona/everest-operator/pull/714 is merged

EVEREST-1625 align helm and operator crds

---

charts/everest/README.md
charts/everest/values.yaml

We forked OLM to fix the bug that was blocking installation on GKE autopilot clusters.
See the PR for more info:
https://github.com/percona/operator-lifecycle-manager/pull/1

EVEREST-343 use percona/olm fork image

---

charts/pxc-db/Chart.yaml
charts/pxc-db/README.md

The extra line breaks were causing rendering errors in the markdown

Fix broken values chart in PXC-DB README

---

charts/pg-operator/templates/NOTES.txt

According to the [Helm documentation on custom resource definitions](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/), starting with Helm 3, the crds/ directory is used to automatically install CRDs required for Operator deployments.
During installation, a CRD from the crds/ directory is only applied if it does not already exist in the cluster. If it exists, Helm will skip it and print a warning. However, during upgrades, Helm always skips applying CRDs, without attempting to check or update them.
To provide better guidance to users during Helm upgrades, a warning can now be displayed based on the CRD version, extracted from the pgv2.percona.com/version label. This helps inform users when a newer version of the CRDs is available without automatically applying them. …

K8SPG-723 Add CRD warning for Helm upgrade

---

charts/pxc-operator/crds/crd.yaml

This change the following labels used to crarify relation between  CRD and Operator version:
```
app.kubernetes.io/component: crd
app.kubernetes.io/name: percona-xtradb-cluster
app.kubernetes.io/part-of: percona-xtradb-cluster-operator
app.kubernetes.io/version: v<version>
```

K8SPXC-1569 add version label to crd.yaml

---

charts/everest/README.md
charts/everest/templates/_helpers.tpl
charts/everest/values.yaml

Running `helm upgrade` can cause the `webhook-server-cert` Secret content to change. This can have some unintended consequences.
- introduce a new `preserveTLSCerts` value (default is `true`) that will allow you to preserve TLS Secret during helm upgrade
- this field is ignored during installation, or if Secrets are explicitly specified

EVEREST-2279 | Allow preserving webhook server TLS certificates during helm upgrades

---

charts/everest/Chart.lock
charts/everest/README.md
charts/everest/charts/common/Chart.yaml
charts/everest/charts/common/README.md
charts/everest/charts/common/templates/_csv_cleanup.yaml.tpl
charts/everest/charts/common/templates/_db_resources_cleanup.yaml.tpl
charts/everest/charts/common/templates/_operators_installer.yaml.tpl
charts/everest/charts/common/templates/_psp_cleanup.yaml.tpl
charts/everest/charts/common/templates/_upgrade_checks.yaml.tpl
charts/everest/charts/everest-db-namespace/Chart.lock
charts/everest/charts/everest-db-namespace/README.md
charts/everest/charts/everest-db-namespace/templates/hooks.yaml
charts/everest/charts/everest-db-namespace/values.yaml
charts/everest/templates/hooks.yaml
charts/everest/values.yaml

Everest Helm chart uses the `bitnami/kubectl` Docker image to execute some chart hooks. However, the `bitnami` registry is planned for deletion - https://github.com/bitnami/charts/issues/35164
- move to `bitnamilegacy/kubectl` temporarily. We might eventually need to build are own image, but this will buy us some extra time
- provide a way to override the image used in the chart hook so that we are not so tightly dependent on an external vendor, and have the flexibility to use alternate images in such situations

EVEREST-2303 | Move from bitnami/kubectl image

---

charts/pmm-ha/charts/pg-db/values.yaml
charts/pmm-ha/values.yaml

This pull request updates the PostgreSQL host-based authentication (pg_hba) configuration for Patroni to better support common private network ranges used in Kubernetes environments. The main change is a shift from hardcoded network ranges to a more flexible and comprehensive configuration that covers major cloud providers and on-prem setups.
**Patroni configuration updates:**
* In `charts/pmm-ha/values.yaml`, the `pg_hba` entries under `patroni.dynamicConfiguration.postgresql` have been updated to allow connections from RFC1918 private networks (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16) for both `gfuser` and `pmmuser`, improving compatibility with AWS, GCP, Azure, Docker, minikube, and on-prem environments.
* In `charts/pmm-ha/charts/pg-db/values.yaml`, the previous hardcoded `pg_hba` …

PMM-14364 Fix Patroni's pg_hba subnets
