- README.md
Signed-off-by: Paul Czarkowski <username.taken@gmail.com>
> update readme with correct url for percona-db chart.

- .circleci/config.yml
- .github/workflows/release.yaml
- .github/workflows/test.yaml
- ct.yaml
Before this is merged we need a secret added to the repo named `CR_TOKEN`  see https://github.com/helm/charts-repo-actions-demo#prerequisites
Signed-off-by: Paul Czarkowski <username.taken@gmail.com>
> switch from circle to gh actions

- charts/pxc-db/Chart.yaml
- charts/pxc-db/crds/crd.yaml
- charts/pxc-db/production-values.yaml
- charts/pxc-db/templates/cluster-secret.yaml
- charts/pxc-db/templates/cluster.yaml
- charts/pxc-db/values.yaml
- charts/pxc-operator/Chart.yaml
- charts/pxc-operator/crds/crd.yaml
- charts/pxc-operator/templates/deployment.yaml
- charts/pxc-operator/templates/role-binding.yaml
- charts/pxc-operator/values.yaml
Opened a ticket for delete-haproxy-pvc finalizer here: https://jira.percona.com/browse/K8SPXC-400
> K8SPXC-401 - Update for PXC operator v1.5.0 release

- README.md
- charts/psmdb-db/README.md
- charts/psmdb-operator/README.md
- charts/pxc-operator/README.md
Additionally we need to update:
helm/hub (as part of K8SPSMDB-226) with something like this:
https://github.com/tplavcic/hub/commit/bd76ea3f2a192159c074c65098a51e8f0938514f
let's discuss if we will use eng-cloud@percona.com etc.
> K8SPSMDB-226 - Fix readme for PSMDB and percona-lab

- charts/pxc-db/README.md
I've detected that some documentation in the README.md is out of sync with the values.yaml and updated it accordingly.
PS: If you accept this PR, any chance to get a `hacktoberfest-accepted` label? ;)
> Sync values documencation to values.yaml

- charts/pxc-db/Chart.yaml
- charts/pxc-db/templates/cluster.yaml
> K8SPXC-495 - use templating in Values.yml for pxc.configuration and pxc.resources

- .github/workflows/release.yaml
- .github/workflows/test.yaml
Checked test run on PSMDB 1.6.0 release change here:
https://github.com/tplavcic/helm-test/runs/1625520315?check_suite_focus=true
Checked that the releases were created here:
https://github.com/tplavcic/helm-test/releases/tag/psmdb-db-0.1.1
https://github.com/tplavcic/helm-test/releases/tag/psmdb-operator-0.1.1
> CLOUD-603 - Update GitHub actions to latest versions

- charts/psmdb-db/Chart.yaml
- charts/psmdb-db/README.md
- charts/psmdb-db/crds/crd.yaml
- charts/psmdb-db/production-values.yaml
- charts/psmdb-db/templates/NOTES.txt
- charts/psmdb-db/templates/cluster-secret.yaml
- charts/psmdb-db/templates/cluster.yaml
- charts/psmdb-db/values.yaml
- charts/psmdb-operator/Chart.yaml
- charts/psmdb-operator/crds/crd.yaml
- charts/psmdb-operator/templates/NOTES.txt
- charts/psmdb-operator/templates/deployment.yaml
- charts/psmdb-operator/templates/role-binding.yaml
- charts/psmdb-operator/templates/role.yaml
- charts/psmdb-operator/values.yaml
Notice the default here is PSMDB 4.4 at the moment - maybe need to discuss more or change back to 4.2.
> Update PSMDB chart for 1.6.0 release

- charts/psmdb-db/Chart.yaml
- charts/psmdb-db/values.yaml
- charts/pxc-db/Chart.yaml
- charts/pxc-db/README.md
- charts/pxc-db/crds/crd.yaml
- charts/pxc-db/production-values.yaml
- charts/pxc-db/templates/cluster-secret.yaml
- charts/pxc-db/templates/cluster.yaml
- charts/pxc-db/values.yaml
- charts/pxc-operator/Chart.yaml
- charts/pxc-operator/README.md
- charts/pxc-operator/crds/crd.yaml
- charts/pxc-operator/templates/deployment.yaml
- charts/pxc-operator/templates/role-binding.yaml
- charts/pxc-operator/templates/role.yaml
- charts/pxc-operator/values.yaml
This makes an update for PXCO 1.7.0 release and includes PR's #21 and #42
> Update for PXCO 1.7.0 release

- .github/ct.yaml
- .github/workflows/test.yaml
- charts/psmdb-db/Chart.yaml
- charts/psmdb-db/README.md
- charts/psmdb-db/crds/crd.yaml
- charts/psmdb-db/production-values.yaml
- charts/psmdb-db/templates/NOTES.txt
- charts/psmdb-db/templates/cluster.yaml
- charts/psmdb-db/values.yaml
- charts/psmdb-operator/Chart.yaml
- charts/psmdb-operator/README.md
- charts/psmdb-operator/crds/crd.yaml
- charts/psmdb-operator/templates/role.yaml
- charts/psmdb-operator/values.yaml
- ct.yaml
**BREAKING CHANGES**: replicaset is now replicasets array !
example:
`helm install --values production-values.yaml --namespace=helm-test cluster1 . --set replset.volumeSpec.pvc.resources.requests.storage=10Gi`
is now becoming:
`helm install --values production-values.yaml --namespace=helm-test cluster1 . --set "replsets[0].volumeSpec.pvc.resources.requests.storage=10Gi"`
**NOTE:** Decision about the chart versions needs to be made prior to merging!
> Update for PSMDBO 1.7.0 release

- charts/pxc-db/Chart.yaml
- charts/pxc-db/README.md
- charts/pxc-db/crds/crd.yaml
- charts/pxc-db/production-values.yaml
- charts/pxc-db/templates/_helpers.tpl
- charts/pxc-db/templates/cluster.yaml
- charts/pxc-db/templates/s3-secret.yaml
- charts/pxc-db/values.yaml
- charts/pxc-operator/Chart.yaml
- charts/pxc-operator/README.md
- charts/pxc-operator/crds/crd.yaml
- charts/pxc-operator/values.yaml
Update for PXCO 1.8.0 release and merge community PRs #39 #66 #67
> K8SPXC-674 - Update for PXCO 1.8.0 release and merge community contributions

- charts/pxc-db/README.md
I have described the finalizers in 'README.md' file within pxc-db folder. I have added a three rows in configurable parameters table.
> Finalizers described

- charts/pxc-db/Chart.yaml
- charts/pxc-db/README.md
- charts/pxc-db/crds/crd.yaml
- charts/pxc-db/production-values.yaml
- charts/pxc-db/templates/_helpers.tpl
- charts/pxc-db/templates/cluster-secret.yaml
- charts/pxc-db/templates/cluster.yaml
- charts/pxc-db/values.yaml
Add proxysql and haproxy configuration fields.
> K8SPXC-771 - add-configuration for proxysql and haproxy

- charts/psmdb-db/Chart.yaml
- charts/psmdb-db/README.md
- charts/psmdb-db/production-values.yaml
- charts/psmdb-db/templates/cluster.yaml
- charts/psmdb-db/values.yaml
This partially fixes some of the errors from K8SPSMDB-541 (other part will be documented) and also merged community contribution from PR #84
> K8SPSMDB-541 - Fix errors in psmdb-db chart and merge PR #84

- charts/pxc-db/Chart.yaml
- charts/pxc-db/README.md
- charts/pxc-db/production-values.yaml
- charts/pxc-db/templates/cluster.yaml
- charts/pxc-db/values.yaml
- charts/pxc-operator/Chart.yaml
- charts/pxc-operator/README.md
- charts/pxc-operator/templates/NOTES.txt
- charts/pxc-operator/templates/deployment.yaml
- charts/pxc-operator/templates/role-binding.yaml
- charts/pxc-operator/templates/role.yaml
- charts/pxc-operator/values.yaml
This merges following PR's for PXCO helm charts: #70, #73, #74, #77 and #81
> Merge community contributions for PXC helm charts

- charts/pxc-db/Chart.yaml
- charts/pxc-db/templates/cluster.yaml
- charts/pxc-db/values.yaml
Enable resources managment to avoid duplicate resources in containers.
> [pxc-db] Add resources to sidecars, pmm and logcollector

- charts/psmdb-db/Chart.yaml
- charts/psmdb-db/README.md
- charts/psmdb-db/crds/crd.yaml
- charts/psmdb-db/production-values.yaml
- charts/psmdb-db/templates/cluster.yaml
- charts/psmdb-db/values.yaml
- charts/psmdb-operator/Chart.yaml
- charts/psmdb-operator/README.md
- charts/psmdb-operator/crds/crd.yaml
- charts/psmdb-operator/values.yaml
1. Updated PSMDB charts for release 1.10.0
2. Merges community contribution from PR #93
> K8SPSMDB-554 - Update PSMDB charts for 1.10.0 release

- charts/pg-db/Chart.yaml
- charts/pg-db/README.md
- charts/pg-db/production-values.yaml
- charts/pg-db/templates/cluster.yaml
- charts/pg-db/values.yaml
- Tls settings added
- Scheduled backup settings added
> K8SPG-128 PG database 1.0.0 chart

- charts/pxc-db/Chart.yaml
- charts/pxc-db/README.md
- charts/pxc-db/crds/crd.yaml
- charts/pxc-db/production-values.yaml
- charts/pxc-db/templates/cluster.yaml
- charts/pxc-db/values.yaml
- charts/pxc-operator/Chart.yaml
- charts/pxc-operator/README.md
- charts/pxc-operator/crds/crd.yaml
- charts/pxc-operator/templates/deployment.yaml
- charts/pxc-operator/values.yaml
This merges community contributions from PR's: #99, #100 and #101
> K8SPXC-895 - Update for PXC Operator release 1.10.0

- charts/pxc-operator/Chart.yaml
- charts/pxc-operator/values.yaml
https://jira.percona.com/browse/K8SPXC-901
Add default resources to `pxc-operator/values.yaml`
> K8SPXC-901: Add default resource limits for Operator's pod containers

- charts/psmdb-db/Chart.yaml
- charts/psmdb-db/README.md
- charts/psmdb-db/crds/crd.yaml
- charts/psmdb-db/production-values.yaml
- charts/psmdb-db/templates/cluster-secret.yaml
- charts/psmdb-db/templates/cluster.yaml
- charts/psmdb-db/values.yaml
- charts/psmdb-operator/Chart.yaml
- charts/psmdb-operator/README.md
- charts/psmdb-operator/crds/crd.yaml
- charts/psmdb-operator/values.yaml
Update for release + merge of community PR's: #106 and #98
> K8SPSMDB-571 - Update for PSMDB Operator release 1.11.0

- charts/psmdb-db/README.md
- charts/psmdb-db/templates/cluster.yaml
https://jira.percona.com/projects/K8SPSMDB/issues/K8SPSMDB-592
> [K8SPSMDB-592] Fix property names related to Mongos exposure

- charts/psmdb-operator/README.md
Renew the page
Update the naming
Add instructions for DB
> Update README.md - mongo operator

- charts/psmdb-db/README.md
Renew
Update instructions and links
> Update README.md - psmdb

- README.md
relative links do not work in ghpages
> Update README.md - ghpages

- charts/pg-operator/README.md
Change naming
Correct command
Add helm chart deployment for DB
> Update README.md - pg operator

- charts/pg-db/README.md
Remove noise
Update the naming
Add more links
> Update README.md - pg distribution

- charts/pxc-db/Chart.yaml
- charts/pxc-db/README.md
- charts/pxc-db/production-values.yaml
- charts/pxc-db/templates/cluster.yaml
- charts/pxc-db/values.yaml
This is a merge for PR's #123, #124 and #133
> Merge community contributions

- charts/pxc-db/Chart.yaml
- charts/pxc-db/README.md
- charts/pxc-db/production-values.yaml
- charts/pxc-db/templates/cluster.yaml
- charts/pxc-db/values.yaml
Adding missing options supported in PXC operator but not present in Helm Chart.
> K8SPXC-957 adding missing operator options to helm chart

- charts/psmdb-db/Chart.yaml
- charts/psmdb-db/README.md
- charts/psmdb-db/production-values.yaml
- charts/psmdb-db/templates/cluster.yaml
- charts/psmdb-db/values.yaml
for replicasets and config replica set
> K8SPSMDB-627 - Add serviceAnnotations and loadBalancerSourceRanges

- charts/pmm/Chart.yaml
- charts/pmm/README.md
- charts/pmm/templates/ingress.yaml
- charts/pmm/templates/statefulset.yaml
- charts/pmm/values.yaml
https://jira.percona.com/browse/PMM-10102
- updated to 2.29.0
- removed init controller (new feature in 2.29.0)
- removed special env - GF_ should be used instead
- improved doc as was suggested during 2.29.0 doc review
> update to 2.29.0 and small improvements

- charts/pmm/Chart.yaml
- charts/pmm/values.yaml
> Update pmm to 2.29.1

- charts/pxc-db/Chart.yaml
- charts/pxc-db/templates/NOTES.txt
Minor fixes for the Notes of a helm chart.
> K8SPXC-1070 Update NOTES.txt

- charts/pg-db/Chart.yaml
- charts/pg-db/README.md
- charts/pg-db/templates/cluster.yaml
- charts/pg-db/values.yaml
The operator has been falling into error when loadBalancerSourceRanges
was specified due to incorrect logic inside template.
> K8SPG-192 Fix for LB source ranges logic

- CONTRIBUTING.md
- README.md
- charts/pg-operator/Chart.yaml
- charts/pg-operator/templates/NOTES.txt
- charts/ps-db/Chart.yaml
- charts/ps-db/README.md
- charts/ps-operator/Chart.yaml
- charts/ps-operator/templates/NOTES.txt
- charts/psmdb-operator/Chart.yaml
- charts/psmdb-operator/templates/NOTES.txt
- charts/pxc-operator/Chart.yaml
- charts/pxc-operator/templates/NOTES.txt
Change the wording and ensure that we produce coherent NOTES for all Operators.
> CLOUD-738 Fixing notes to make them sexier

- charts/psmdb-operator/Chart.yaml
- charts/psmdb-operator/README.md
- charts/psmdb-operator/templates/deployment.yaml
- charts/psmdb-operator/values.yaml
Thank you for the operator. Very useful for me.
I've add `securityContext` to avoid warning messages on deploy process. 
`podAnnotations` helps to prometheus to collect operator metrics.
Thank you.
> K8SPSMDB-890 - Add pod/container security context

- charts/pg-db/Chart.yaml
- charts/pg-db/README.md
- charts/pg-db/templates/NOTES.txt
- charts/pg-db/templates/cluster.yaml
- charts/pg-operator/Chart.yaml
**Fixes**
In pg operator:
- just a minor wording change
In pg-db chart:
- Changed Examples in the readme, verified them
- Changed NOTES.txt - we were using commands from v1 operator
- Added support of finalizers
- Fixed users configuration
> K8SPG-406 Fixes in helm

- charts/psmdb-db/Chart.yaml
- charts/psmdb-db/README.md
- charts/psmdb-db/templates/cluster.yaml
- charts/psmdb-db/values.yaml
- charts/psmdb-operator/Chart.yaml
- charts/psmdb-operator/README.md
- charts/psmdb-operator/crds/crd.yaml
- charts/psmdb-operator/templates/deployment.yaml
- charts/psmdb-operator/templates/role.yaml
- charts/psmdb-operator/values.yaml
This adds:
K8SPSMDB-886 - Update for 1.15.0 release for psmdb-db and psmdb-operator charts
K8SPSMDB-997 - Add serviceAccountName to the existing resources (PR https://github.com/percona/percona-helm-charts/pull/242)
> K8SPSMDB-886 - Update psmdb-db and psmdb-operator charts for 1.15.0 release

- .github/CODEOWNERS
Let's update it according to current roles
> Update CODEOWNERS for pmm helm

- charts/pxc-db/Chart.yaml
- charts/pxc-db/templates/cluster.yaml
> Add containerSecurityContext for pmm

- charts/pg-operator/Chart.yaml
- charts/pg-operator/values.yaml
- charts/pmm/Chart.yaml
- charts/pmm/values.yaml
Roll out registry proxy to capture more insights. Phase 1.
> CLOUD-831 rolling out registry proxy by default

- .gitignore
- charts/pmm/Chart.yaml
- charts/pmm/templates/_helpers.tpl
https://jira.percona.com/browse/PMM-12586
> PMM-12586 Automatically apply changes to the pmmEnv

- charts/pg-db/Chart.yaml
- charts/pg-db/values.yaml
- charts/pg-operator/Chart.yaml
- charts/pg-operator/values.yaml
- charts/pmm/Chart.yaml
- charts/pmm/values.yaml
Removing registry-1 as project was cancelled.
> CLOUD-831 remove registry-1

- charts/psmdb-operator/Chart.yaml
- charts/psmdb-operator/README.md
- charts/psmdb-operator/templates/deployment.yaml
- charts/psmdb-operator/values.yaml
Hi,
added labels and podLabels in values.yaml and updated the deployment.yaml to reflect that
> K8SPSMDB-1049 - psmdb-operator - add option for pod and deployment labels

- charts/pg-db/templates/cluster.yaml
There are several variable/template values that are un-wrapped, which cause compilation issues in helm, for pg-db. This fixes those, and also a few lint issues.
> K8SPG-529  - Fix lint issues and un-wrapped template values

- README.md
Have it synced with our readme page.
> Update README.md on gh-page

- charts/pg-db/Chart.yaml
- charts/pg-db/templates/cluster.yaml
- charts/pg-operator/Chart.yaml
- charts/pg-operator/templates/deployment.yaml
- charts/pg-operator/templates/role-binding.yaml
- charts/pg-operator/templates/role.yaml
Relates to:
https://perconadev.atlassian.net/browse/K8SPG-585
and https://github.com/percona/percona-helm-charts/issues/328
> K8SPG-585 - PG - Add namespace to templates

- charts/pxc-operator/Chart.yaml
- charts/pxc-operator/README.md
I added `watchAllNamespaces` option in the customization section.
It was in values but I couldn't find it (in README) in the first place for my usage so I thought it's a good idea.
> Update README.md to add watchAllNamespaces option

- charts/pg-db/Chart.yaml
- charts/pg-db/README.md
- charts/pg-db/templates/cluster.yaml
- charts/pg-db/values.yaml
Fix patroni.dynamicConfiguration and add patroni.switchover that was in docs but not implemented in the chart.
> K8SPG-607: Fix patroni.dynamicConfiguration in pg-db

- charts/psmdb-db/Chart.yaml
- charts/psmdb-db/templates/cluster.yaml
`psmdb-db` chart - Allow secrets names to be templated.
> K8SPSMDB-1142 - Make secrets templatable in values.yaml file

- charts/psmdb-db/README.md
- charts/psmdb-db/templates/cluster.yaml
- charts/psmdb-db/values.yaml
- charts/psmdb-operator/crds/crd.yaml
https://perconadev.atlassian.net/browse/K8SPSMDB-1160
> K8SPSMDB-1160: disable pvc resizing by default

- .github/workflows/test.yaml
- charts/everest/Makefile
Looks like you need to update Chart.lock after updating the verrion in Chart.yaml
> Fix Everest chart release workflow

- .github/workflows/release.yaml
- .github/workflows/test.yaml
Update outdated and no longer supported github action versions.
> Update actions versions

- charts/everest/crds/olm.yaml
- charts/everest/templates/everest-operator/manager.clusterrole.yaml
copied from https://github.com/percona/everest-operator/blob/main/deploy/bundle.yaml
> EVEREST-107 | Update operator RBAC

- charts/pxc-db/README.md
- charts/pxc-db/templates/cluster.yaml
- charts/pxc-db/values.yaml
> K8SPXC-377: PXC User Management

- README.md
- charts/pg-db/README.md
- charts/pg-operator/README.md
- charts/pmm/README.md
- charts/psmdb-db/README.md
- charts/psmdb-operator/README.md
- charts/pxc-db/README.md
- charts/pxc-operator/README.md
subj, no need for version bumps, just readmes
> [CLOUD-878] Minor fixes to readmes and links

- charts/everest/Chart.lock
- charts/everest/charts/common/Chart.yaml
- charts/everest/charts/common/README.md
- charts/everest/charts/common/templates/_upgrade_checks.yaml.tpl
- charts/everest/charts/everest-db-namespace/Chart.lock
* Does not correctly resolve the CLI binary URL
* Requires new permissions to work correctly
> EVEREST-1746 | Fix broken script in pre-upgrade hook

- charts/everest/README.md
- charts/everest/README.md.gotmpl
- charts/everest/docs/openshift.md
- charts/everest/templates/ksm-openshift-clusterrolebinding.yaml
- also adds an additional manifest for openshift compatibly
> EVEREST-107 | add docs for openshift

- charts/everest/crds/everest.yaml
- charts/everest/values.yaml
Related PRs:
* https://github.com/percona/everest/pull/1063
> EVEREST-1799 add scope field in oidc

- charts/everest/README.md
- charts/everest/templates/everest-server/service.yaml
- charts/everest/values.yaml
Expose fields for configuring the everest server service type and port
> EVEREST-1856 expose server service

- charts/everest/templates/everest-operator/manager.clusterrole.yaml
**Related pull requests**
- https://github.com/percona/everest/pull/1235
- https://github.com/percona/everest-operator/pull/704
> EVEREST-1930 add permissions to read pods

- charts/everest/README.md
- charts/everest/templates/everest-server/ingress.yaml
- charts/everest/templates/everest-server/service.yaml
- charts/everest/values.yaml
i created a draft for including ingress for the everest server
I have seen need for it for many that adds it manual, but i think in the chart would be better
Fixes https://github.com/percona/percona-helm-charts/issues/520
> An ingress for everest server

- charts/everest/templates/everest-operator/webhook.yaml
EVEREST-1961
add monitoringconfig validation webhook
Related PRs:
- https://github.com/percona/everest-operator/pull/816
- https://github.com/percona/everest/pull/1490
> EVEREST-1961 validate monitoring WH

- .github/workflows/everest-pr-checks.yaml
- charts/everest/charts/everest-crds/Makefile
The same version is used in everest-operator repo
> Update kustomize version to 5.7.0

- .github/workflows/everest-pr-checks.yaml
- charts/everest/Chart.lock
- charts/everest/README.md
- charts/everest/charts/common/Chart.yaml
- charts/everest/charts/common/README.md
- charts/everest/charts/common/templates/_lbc_cleanup.yaml.tpl
- charts/everest/charts/everest-crds/templates/apiextensions.k8s.io_v1_customresourcedefinition_databaseclusters.everest.percona.com.yaml
- charts/everest/charts/everest-db-namespace/Chart.lock
- charts/everest/templates/everest-operator/deployment.yaml
- charts/everest/templates/everest-operator/loadbalancerconfig.yaml
- charts/everest/templates/hooks.yaml
- charts/everest/values.yaml
EVEREST-2177 
Add default lbc, initContainer and lbc cleanup
Related PRs:
- https://github.com/percona/everest/pull/1590
- https://github.com/percona/everest-operator/pull/861
> EVEREST-2177 Add default lbc, initContainer and lbc cleanup

- charts/pmm-ha/templates/haproxy-configmap.yaml
- charts/pmm-ha/values.yaml
- Disabled the default HAProxy configmap creation in values.yaml to allow for custom configurations.
- Introduced a new ConfigMap template for HAProxy configuration, enhancing flexibility and maintainability.
> PMM-13854 - Refactor HAProxy configuration management
